import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:maakview_app/utils/term_and_condition_font.dart';

class Condition extends StatelessWidget {
   Condition({Key? key}) : super(key: key);

   String one = '1.1 These terms and conditions outline the rules and regulations for the use of Maakview.com Limited’s Website, located a www.Maakview.com'+
   '1.2 By accessing this website we assume you accept these terms and conditions. Maakview.com Limited provides access to the maakview.com website or the mobile application/app or any other media("Website") to you subject to the terms and conditions (“Terms”) set out on this page. By using the Site, you hereby accept these terms and conditions (including the linked information herein) and represent that you agree to comply with these terms and conditions (the "User Agreement"). Please read them carefully as your continued usage of the Website, you signify your agreement to be bound by these Terms. If you do not want to be bound by the Terms, you must not subscribe to or use the Website or our services'+
   '1.3 This document is an electronic record in terms of Information Technology Act, 2006 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2006. This electronic record is generated by a computer system and does not require any physical or digital signatures.'
   '1.4 The Website is operated by Maakview.com Limited., a company incorporated under the laws of Bangladesh having its registered office at Rahima Plaza (6th floor, 82/3 Laboratory Rd, Dhaka 1205, Bangladesh.'+
   '1.5 When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.'
   ;

   String two = '2.1 Transaction on the Platform and Use of the Website is available only to persons who can form legally binding contracts under Contract Act, 1872.'+
   '2.2 If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent ormlegal guardian.'+
   '2.3 As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Maakview reserves the right to terminate your membership and  or refuse to provide you with access to the Platform if it is brought to Maakview\'s notice or if it is discovered that You are under the age of 18 years and transacting on the Platform';

   String three = '3.1 If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.'+
   '3.2 If you wish to register your account with the Website, you shall be required to create an account by registering with a valid Bangladeshi mobile number and/or with your Facebook account or your email address or by filling in the details prescribed in the Website registration form. You will then receive a password or one-time PIN with which you can login to the website to place orders.'+
   '3.3.a You agree that Maakview shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.'+
   '3.3.b If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.';

   String four = '4.1 When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.';

   String five = '5.1 The Website is a platform that Users utilize to meet and interact with one another for their transactions. Maakview is not and cannot be a party to or control in any manner any transaction between the Platforms Users.'+
   '5.2 All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, warranties related to products and services and after sales services related to products and services. Maakview does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Maakview.'
   '5.3 You agree, understand and acknowledge that the Site is an online platform that enables you to purchase products listed at the price indicated therein at any time from any location using a payment method of your choice. You further agree and acknowledge that we are only a facilitator and cannot be a party to or control in any manner any transactions on the Site or on a payment gateway as made available to you by an independent service provider. Accordingly, the contract of sale of products on the Site shall be a strictly bipartite contract between you and the sellers on our Site while the payment processing occurs between you, the service provider and in case of prepayments with electronic cards your issuer bank. Accordingly, the contract of payment on the Site shall be strictly a bipartite contract between you and the service provider as listed on our Site'
   '5.4 Maakview does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. Maakview does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. Maakview accepts no liability for any errors or omissions, whether on behalf of itself or third parties.'
   '5.5 Maakview is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.'
   '5.6 Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller\'s acceptance of Buyer\'s offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual\'s consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.'
   ;

   String six = '6.1 Membership on the Platform is free for buyers. Maakview does not charge any fee for browsing and buying on the Platform. Maakview reserves the right to change its Fee Policy from time to time. In particular, Maakview may at its sole discretion introduce new services and modify some or all of the existing services offered on the Platform. In such an event Maakview reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in BDT. You shall be solely responsible for compliance of all applicable laws including those in Bangladesh for making payments to Maakview.com Private Limited.';


   String seven = '7.1 The material (including the content, and any other content, software or services) contained on Maakview.com are the property of Maakview.com Limited, its subsidiaries, affiliates and/or third party licensors. No material on this site may be copied, reproduced, republished, installed, posted, transmitted, stored or distributed without written permission from Maakview.com Limited.'+
   '7.2 Our graphics, logos, page headers, button icons, scripts and service names are the trademarks or trade dress and may not be used in connection with any product or service that does not belong to us or in any manner that is likely to cause confusion among customers, or in any manner that disparages or discredits us. All other trademarks that appear on this Site are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by us.'
   ;

   String eight = '8.1 To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:'+
   '8.2 We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the products listed or displayed or transacted or the content (including product or pricing information and/or specifications) on the Site. While we have taken precautions to avoid inaccuracies in content, this Site, all content, information (including the price of products), software, products, services and related graphics are provided as is basis, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any products on the Site. At no time shall any right, title or interest in the products sold through or displayed on the Site vest with us nor shall Maakview have any obligations or liabilities in respect of any transactions on the Site.'
   ;

   String nine = '9.1 This site uses cookies, which means that you must have cookies enabled on your computer in order for all functionality on this site to work properly. A cookie is a small data file that is written to your hard drive when you visit certain Web sites. Cookie files contain certain information, such as a random number user ID that the site assigns to a visitor to track the pages visited. A cookie cannot read data off your hard disk or read cookie files created by other sites. Cookies, by themselves, cannot be used to find out the identity of any user.';

   String ten = ' Maakview we do not warrant that Product description or other content of this Platform is accurate, complete, reliable, current, or error-free and assumes no liability in this regard.';

   String eleven = '11.1 Please review our Privacy Agreement, which also governs your visit to the Site. The personal information / data provided to us by you or your use of the Site will be treated as strictly confidential, in accordance with the Privacy Agreement and applicable laws and regulations. If you object to your information being transferred or used in the manner specified in the Privacy Agreement, please do not use the Site.';

   String twelve = '12.1 Maakview, itself does not produce or manufacture any product, therefore Maakview tries to control the quality, but do not give quality assurance for any. We believe the manufacturer/ vendor/ supplier are fully capable of assuring the quality of every product'+
   '12.2 All products displayed on the website are subject to change and are subject to availability.'
   ;

   String thirteen = '13.1 You may use the software solely for purposes of enabling you to use and enjoy our services as permitted by the Terms and Conditions and any related applicable terms as available on the Site. You may not incorporate any portion of the Software into your own programs or compile any portion of it in combination with your own programs, transfer it for use with another service, or sell, rent, lease, lend, loan, distribute or sub-license the Software or otherwise assign any rights to the Software in whole or in part. You may not use the Software for any illegal purpose. We may cease providing you service and we may terminate your right to use the Software at any time. Your rights to use the Software will automatically terminate without notice from us if you fail to comply with any of the Terms and Conditions listed here or across the Site. Additional third party terms contained within the Site or distributed as such that are specifically identified in related documentation may apply and will govern the use of such software in the event of a conflict with these Terms and Conditions. All software used in any of our services is our property and/or our affiliates or its software suppliers and protected by the laws of Bangladesh including but not limited to any other applicable copyright laws.'+
   '13.2 Updates: In order to keep the Maakview Software / Application/ App up-to-date, we may offer automatic or manual updates at any time and without notice to you'
   ;

   String fourteen = '14.1 Please read these conditions carefully before placing an order for any products with the Sellers (“We” or “Our” or “Us”, wherever applicable) on the Site. These conditions signify your agreement to be bound by these conditions.';

   String fifteen = '15.1 Maakview reserves the right to modify these Terms and Conditions. Such modifications shall be effective immediately upon posting on Maakview.com. You are responsible for the reviewing of such modifications. Your continued access or use of Maakview.com shall be deemed your acceptance of the modified terms and conditions.'+
   '5.2  Stock availability: The orders are subject to availability of stock.'+
   '5.3 Delivery Timeline: The delivery might take longer than usual timeframe/line to be followed by Maakview.'
   ;


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        //backgroundColor: Colors.indigo[800],
        toolbarHeight: 148,
        title: Column(
          children: [
            Text(
              'Terms & Condition',
              style: GoogleFonts.poppins(
                  textStyle: TextStyle(
                fontSize: 20.0,
                fontWeight: FontWeight.w600,
              )),
            ),
          ],
        ),
      ),
      body: Padding(
        padding: EdgeInsets.fromLTRB(23, 52, 17, 0),
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              KtextFontHeadline(text: '1. Terms of Use'),
              SizedBox(
                height: 7,
              ),
              Text(one,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 20,
              ),
              KtextFontHeadline(text: '2. Membership Eligibility'),
              SizedBox(
                height: 7,
              ),
              Text(two
                ,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 20,
              ),
              KtextFontHeadline(text: '3. Your Account and Registration'),
              SizedBox(
                height: 7,
              ),
              Text(
                three,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),
              SizedBox(
                height: 20,
              ),
              KtextFontHeadline(text: '4. Communications'),
              SizedBox(
                height: 7,
              ),
              Text(
                four,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '5. Platform for Transaction and Communication'),
              SizedBox(
                height: 7,
              ),

              Text(
                five,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '6. Charges'),
              SizedBox(
                height: 7,
              ),
              Text(
                six,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '7. TRADEMARKS AND COPYRIGHTS'),
              SizedBox(
                height: 7,
              ),
              Text(
                seven,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '8. DISCLAIMER'),
              SizedBox(
                height: 7,
              ),
              Text(
                eight,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '9. Cookies'),
              SizedBox(
                height: 7,
              ),
              Text(
                nine,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '9. Cookies'),
              SizedBox(
                height: 7,
              ),

              KtextFontHeadline(text: '10. Product Description'),
              SizedBox(
                height: 7,
              ),
              Text(
                ten,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),
              KtextFontHeadline(text: '11. Privacy'),
              SizedBox(
                height: 7,
              ),
              Text(
                eleven,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),
              KtextFontHeadline(text: '12. Supply Policy'),
              SizedBox(
                height: 7,
              ),
              Text(
                twelve,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '13. Software Terms'),
              SizedBox(
                height: 7,
              ),
              Text(
                thirteen,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '14. CONDITIONS OF SALE (BETWEEN SELLERS AND CUSTOMERS)'),
              SizedBox(
                height: 7,
              ),
              Text(
                fourteen,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),

              KtextFontHeadline(text: '15. Others)'),
              SizedBox(
                height: 7,
              ),
              Text(
                fifteen,
                style: GoogleFonts.poppins(
                  color: Colors.black,
                ),
              ),


            ],
          ),
        ),
      ),
    );
  }
}
